config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "actuality", to: "pages#actuality"
  resources :workouts do
    resources :workout_sets, only: %i[create]
    resources :trainings, only: %i[create]
  end

  resources :trainings, only: :destroy

  resources :exercices do
    resources :ratings, only: %i[create update]
  end

  resources :sessions, only: %i[create destroy update], as: :gym_session

  resources :users, only: %i[index] do
    get "my_dashboard", to: "users#my_dashboard"
    get "my_workouts", to: "users#my_workouts"
    get "my_sessions", to: "users#my_sessions"
    get "my_exercises", to: "users#my_exercises"
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user

  has_many :workout_sets, dependent: :destroy
  has_many :exercices, through: :workout_sets
  has_many :trainings, dependent: :destroy

  has_one_attached :photo

  def muscles
    array = []
    self.workout_sets.each do |wo_set|
      array << wo_set.exercice.muscle
    end
    array.sort
  end

  def fake_time
    self.workout_sets.map { |wo_set| wo_set.repetition }.sum
  end

  def avg_str
    array = []
    self.exercices.each do |exo|
      exo.ratings.each do |rate|
        array << rate.muscular_effort
      end
    end
    sum = (array.sum / array.size.to_f).round(1)
    sum.nan? ? 0 : sum
  end

  def avg_dex
    array = []
    self.exercices.each do |exo|
      exo.ratings.each do |rate|
        array << rate.flexibility
      end
    end
    sum = (array.sum / array.size.to_f).round(1)
    sum.nan? ? 0 : sum
  end

  def avg_end
    array = []
    self.exercices.each do |exo|
      exo.ratings.each do |rate|
        array << rate.breath_difficulty
      end
    end
    sum = (array.sum / array.size.to_f).round(1)
    sum.nan? ? 0 : sum
  end

  def score
    score = ((self.avg_dex + self.avg_str + self.avg_end) / 3).round(1)
  end

  def muscle_hash
    hash = {}
    Exercice::MUSCLES.each do |element|
      nbr = self.muscles.count(element)
      hash[element.to_sym] = nbr unless nbr == 0
    end
    return hash
  end

  def focus
    if self.avg_str > self.avg_dex && self.avg_str > self.avg_end
      return ["Muscular Effort", "#FD1015", "rgba(255,16,0,1)"]
    elsif self.avg_dex > self.avg_end
      return ["Flexibility", "#1ED584", "rgba(65,255,0,1)"]
    else
      return ["Breath Difficulty", "#73BBC9", "rgba(0,129,255,1)"]
    end
  end

  def styling
    {
      str: {
        value: self.avg_str,
        color: "rgba(255,16,0,1)"
      },
      end: {
        value: self.avg_end,
        color: "rgba(0,129,255,1)"
      },
      dex: {
        value: self.avg_dex,
        color: "rgba(65,255,0,1)"
      }
    }
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[edit update show destroy]

  def index
    Workout.all.find_all { |wo| wo.workout_sets.empty? }.each { |wo| wo.destroy }

    @workouts = Workout.all
    if params[:query].present? # && !params[:query].empty?
      @query = params[:query]
      @workouts = Workout.where("name ILIKE ?", "%#{params[:query]}%")
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "components/list_workouts", locals: {workouts: @workouts}, formats: [:html] }
    end
  end

  def show
    @training = Training.new
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user = current_user
    if @workout.save
      training = Training.new()
      training.workout = @workout
      training.user = current_user
      training.save
      redirect_to edit_workout_path(@workout)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # à modifier avec wo set
    @exercices = Exercice.search(params.dig(:filter, :query))
    @workout_set = WorkoutSet.new
  end

  def update
    @workout.update(workout_params)
    redirect_to edit_workout_path(@workout)
  end

  def destroy
    @workout.destroy
    redirect_to workouts_path, status: :see_other
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:name, :description)
  end
end

app/views/workouts/edit.html.erb
<div style="min-height: calc(100vh - 258px)" class="bg-form-new">
  <h1 style="margin-left: 20vw;" class="pt-5"><strong class="text-success">Step 2 : </strong>Choose your exercices !</h1>

  <%= render "components/form_edit_woset", workout: @workout, workout_set: @workout_set, exercices: @exercices %>
</div>

app/views/workouts/index.html.erb
<div class="bg-index-wo pt-3" style="min-height: 80vh">
  <div data-controller="ajax" class="container">

    <%= form_with url: workouts_path, method: :get, data: {ajax_target: 'form'}, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control mb-3",
                placeholder: "Find your workout",
                data: { action: "keyup->ajax#searching",
                        ajax_target: "input"
                      }
            %>
        <% end %>
    <div data-ajax-target="list">
      <%= render "components/list_workouts", workouts: @workouts %>
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="bg-form-new d-flex align-items-center justify-content-around px-5" style="min-height: calc(100vh - 100px);">
  <div class="">
      <%= render "components/form_new_wo", workout: @workout%>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="bg-image" style="min-height: 80vh">
    <div class="">

      <div class="card-wo d-flex justify-content-center">

        <%# WORKOUT INFOS CARD %>

        <div class="p-5" style="width: 450px;">
          <div class="sticky border border-success p-3 bg-dark rounded text-light">
            <div name="placer" class="d-flex justify-content-between align-items-center">
              <div name="infos-text">
                <h5 class="text-success"><%= @workout.name %></h5>
                <p><em>Description:</em></p>
                <p><%= @workout.description  %></p>
                <p><em>Specs:</em></p>
                <p><strong><%= @workout.exercices.count %></strong> exercices</p>
              </div>
              <%= render "components/pie_chart", workout: @workout, style: "width: 200px" %>
            </div>


            <p class="text-end" style="backdrop-filter: brightness(1.5);"><%= @workout.user.name %></p>

          <%# ADDING TRAINING %>
              <% train = Training.where(user_id: current_user.id, workout_id: @workout.id) %>
              <% if train.empty? %>
                <div class="mb-3 d-flex justify-content-center">
                    <%= simple_form_for([@workout, @training]) do |f| %>
                        <%= button_tag type: 'submit', class: "submit-button" do %>
                          <i class="far fa-plus-square fa-lg add-btn"></i>
                        <% end %>
                    <% end %>
                </div>
              <% else %>
                  <div class="mb-3 d-flex justify-content-center">
                    <%= link_to training_path(train.first), data: {turbo_method: :delete} do %>
                        <i class="far fa-minus-square fa-lg delete-btn"></i>
                     <% end %>
                  </div>
              <% end %>

          </div>
        </div>


        <%# EXERCICES INFOS %>
        <div class="margin_card mt-5">
          <ul class="list-unstyled">
            <% @workout.workout_sets.each do |workout_set| %>
              <li class="mb-3">
                <%= render "components/card_exo_info", workout_set: workout_set, exercice: workout_set.exercice  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

    </div>

</div>