config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "actuality", to: "pages#actuality"
  resources :workouts do
    resources :workout_sets, only: %i[create]
    resources :trainings, only: %i[create]
  end

  resources :trainings, only: :destroy

  resources :exercices do
    resources :ratings, only: %i[create update]
  end

  resources :sessions, only: %i[create destroy update], as: :gym_session

  resources :users, only: %i[index] do
    get "my_dashboard", to: "users#my_dashboard"
    get "my_workouts", to: "users#my_workouts"
    get "my_sessions", to: "users#my_sessions"
    get "my_exercises", to: "users#my_exercises"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :workouts, dependent: :destroy
  has_many :exercices, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :trainings, dependent: :destroy
  has_many :sessions, through: :trainings, dependent: :destroy

  def week_sessions
    # recuperer les sessions de la semaine en cours
    actual_week = Date.today.cweek
    actual_sessions = []
    self.sessions.each do |session|
      session.programing_at.cweek == actual_week ? actual_sessions << session : nil
    end
    return actual_sessions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_time_zone, if: :user_signed_in?

  def my_dashboard
    @available_workouts = (current_user.trainings + Workout.where(user_id: current_user.id)).uniq
    @start_date = params.fetch(:start_date, Date.today).to_date
    @sessions = current_user.sessions
    @workouts = Training.where(user_id: current_user.id).map(&:workout)
    @hash = {}
    @workouts.each do |workout|
      workout.muscle_hash.each do |key, value|
        @hash[key].nil? ? @hash[key] = value : @hash[key] += value
      end
    end
    @k = []
    @v = []
    @hash.each do |key, value|
      @k << key.to_s
      @v << value
    end
    @actual_sessions = current_user.week_sessions

    @hash_session_exo = {
      Mon: 0,
      Tue: 0,
      Wed: 0,
      Thu: 0,
      Fri: 0,
      Sat: 0,
      Sun: 0
    }

    @actual_sessions.each do |session|
      nbr = session.training.workout.exercices.count

      @hash_session_exo[session.programing_at.strftime('%a').to_sym] += nbr
    end
    @days = []
    @count_exo_day = []
    @hash_session_exo.each do |key, value|
      @days << key.to_s
      @count_exo_day << value
    end

    la = (0..6).map do |nbr|
      array = current_user.week_sessions.find_all { |d| d.programing_at.wday == nbr }.map(&:training).map(&:workout).map(&:score)
      avg = (array.sum / array.size.to_f).round(1)
    end.map { |e| e.nan? ? 0 : e }
    la = la << la.delete_at(0)
    @res = la
    # la.each do |ele|
    #   @res << (ele * 10)
    # end
    # @zeb = current_user.week_sessions.map { |e| "#{e.programing_at.strftime('%a')} / #{e.programing_at.wday}" }
  end

  def my_sessions
    raise
  end

  def my_workouts
    @workouts = current_user.workouts
    @trainings = current_user.trainings
  end

  def my_exercises
    raise
  end

  private

  def set_time_zone
    # Time.zone = current_user.time_zone
  end
end

app/views/users/my_dashboard.html.erb
<div class="d-flex justify-content-center" style="background-color: var(--c-gray-800);">
  <div class="app text-white p-2">
    <%# BANDEAU/NAVBAR %>
    <div name="bandeau sup" class="app-header">
      <h1 class="logo">Fitscale</h1>
      <div class="app-header-navigation">
        <div class="tabs m-2">
          <h5 class="active">Dashboard</h2>
          <h5>Settings</h2>
        </div>

      </div>
        <div class="d-flex align-items-center">
          <h5 class="pe-3"><%= current_user.name %></h2>
          <%= image_tag "profile.jpg", class: "avatar-large dropdown-toggle" %>
        </div>
    </div>

    <%# BODY %>
    <div class="app-body mb-3">

      <%# TAB MENU %>
      <nav>
        <div class="nav nav-tabs border border-0 d-flex flex-column align-items-end" id="nav-tab" role="tablist">
          <button class="nav-link active text-success" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
          <button class="nav-link text-success" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">My sessions</button>
        </div>
      </nav>

      <div name="content" class="tab-content bg-dashboard p-4" id="nav-tabContent" style="width: 50vw">
        <%# TABS %>

        <%# USER STATS %>
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

          <div class="d-flex justify-content-between mb-3" style="width:48vw">
            <div>
              <h1 class="text-color my-3"><strong>Details</strong></h1>
              <p class="text-black ps-3 ">Workouts created : <strong><%= Workout.where(user_id: current_user.id).count %></strong></p>
              <p class="text-black ps-3">Workouts added : <strong><%= Training.where(user_id: current_user.id).count %></strong></p>
              <p class="text-black ps-3">Total workouts : <strong><%= Workout.where(user_id: current_user.id).count + Training.where(user_id: current_user.id).count %></strong></p>
              <p class="text-black ps-3">Sessions : <strong><%= current_user.sessions.count %></strong></p>
              <p class="text-black ps-3">Weakest muscle : <br> <strong class="ps-2"><%= @hash.sort_by{ |_key, value| value }.first[0].to_s %></strong> trained only <%= @hash.sort_by{ |_key, value| value }.first[1].to_s %> times</p>
            </div>
            <div>
              <% if @workouts.size != 0 %>
                <%= render "components/bar_chart_dashboard", k: @k, v: @v  %>
              <% else %>
                <p class="text-success">You don't have any workout yet !</p>
              <% end %>
            </div>

          </div>

          <div style="width: 48vw">
            <%= render "components/multi_bar_chart_dashboard", days: @days, count_exo_day: @count_exo_day, la: @res  %>
          </div>
        </div>

        <%# CALENDAR %>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <%= render "components/calendar", sessions: @sessions %>
          <div>
            <%= render "components/multi_bar_chart_dashboard", days: @days, count_exo_day: @count_exo_day, la: @res  %>
          </div>
        </div>

      </div>
      <%# SIDE MENU WITH SESSIONS %>
      <div name="side menu bg-dashboard">
        <h3 class="text-center">This week's <span class="text-success">sessions</span></h3>
        <ul class="list-unstyled">

          <li class="text-center">
            <button id="to-hover" class="mb-3 btn text-success rounded-5 border border-success" data-bs-toggle="modal" data-bs-target="#new">
              <i class="fa-solid fa-plus"></i>
              <p class="animate__backInDown" id="to-show">Plan your next Session</p>
            </button>
            <%= render "components/modal_session", session: Session.new %>
          </li>
          <% current_user.week_sessions.sort_by(&:programing_at).each do |session| %>

            <%# SINGLE SESSION %>
            <li class="d-flex animate__animated animate__backInRight animate__delay-0.5s">
              <div class="d-flex bg-dark border border-success border border-3 m-2 py-2 ps-3 rounded-start-pill" style="width: 100%">
                <div class="d-flex flex-column justify-content-evenly pe-2" name="icon">
                  <button type="button" class="btn text-success rounded-5" data-bs-toggle="modal" data-bs-target="#<%= session.id %>">
                    <i class="fa-regular fa-pen-to-square edit-btn"></i>
                  </button>

                  <%= link_to gym_session_path(session.id), data: {turbo_method: :delete} do %>
                    <button type="button" class="btn text-success rounded-5">
                      <i class="fa-solid fa-trash delete-btn"></i>
                    </button>
                  <% end %>
                </div>
                <div>
                  <em><%= session.programing_at.strftime("%A") %></em>
                  <h5><%= session.training.workout.name %></h5>
                  <h6><%= session.training.workout.exercices.count %> exercices</h6>
                  <% wo_focus = session.training.workout.focus %>
                  <h6>Focus on <span style="color: <%= wo_focus[1] %>"><%= wo_focus[0] %></span></h6>
                </div>
              </div>
            </li>
          <% end %>
        </ul>

      </div>

    </div>

  </div>
</div>
<div>
  <% current_user.week_sessions.sort_by(&:programing_at).each do |session| %>
    <% session_part = session.id.present? ? session : Session.new %>
    <%= render "components/modal_session", session: session_part %>
<% end %>
</div>

app/views/users/my_workouts.html.erb
<div class="bg-index-wo pt-5" style="min-height: calc(100vh - 258px)">

  <div class="container">

    <h1 class="text-white">My <span class="text-success">workouts</span></h1>

    <div class="row">

      <% @trainings.each do |training| %>
        <div class="col-4 my-3"><%= render "components/workout_card", workout: training.workout %></div>
      <% end %>
    </div>

  </div>
</div>