config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "actuality", to: "pages#actuality"
  resources :workouts do
    resources :workout_sets, only: %i[create]
    resources :trainings, only: %i[create]
  end

  resources :trainings, only: :destroy

  resources :exercices do
    resources :ratings, only: %i[create update]
  end

  resources :sessions, only: %i[create destroy update], as: :gym_session

  resources :users, only: %i[index] do
    get "my_dashboard", to: "users#my_dashboard"
    get "my_workouts", to: "users#my_workouts"
    get "my_sessions", to: "users#my_sessions"
    get "my_exercises", to: "users#my_exercises"
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-left col-md-4 col-sm-6">
    <p class="about">
      <span> About the company</span> Fitscale is a website that allows beginners in sports to record sports exercises.
      You can then save your sessions, your performances and rate your feelings. Fitscale helps you track your progress,
      motivate yourself and share your experiences with other users. Fitscale is the ideal website to start or
      continue doing sports in a fun and effective way.
    </p>
  </div>
  <div class="footer-center col-md-4 col-sm-6">
    <div>
      <i class="fa fa-map-marker"></i>
      <p><span> 107 CRS Balguerie Stuttenberg</span> Bordeaux, France</p>
    </div>
    <div>
      <i class="fa fa-phone"></i>
      <p> (+33) 06 46 27 58 89</p>
    </div>
    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="#"> office@fitscale.com</a></p>
    </div>
  </div>
  <div class="footer-right col-md-4 col-sm-6">
    <h2> Company<span> Fitscale</span></h2>
    <p class="menu">
      <a href="#"> Home</a> |
      <a href="#"> About</a> |
      <a href="#"> Services</a> |
      <a href="#"> Portfolio</a> |
      <a href="#"> News</a> |
      <a href="#"> Contact</a>
    </p>
    <%# <div class="icons">
      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-google-plus"></i></a>
      <a href="#"><i class="fa fa-instagram"></i></a>
    </div> %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg border-bottom border-bottom-dark py-0 sticky-top" data-bs-theme="dark" style="background-color: #363636;">
  <div class="container-fluid ps-0">

    <%# button + logo : %>

    <%= link_to  root_path, class: "navbar-brand text-white ps-3" do%>
      <%= image_tag "logo-2.png", alt: "logo.png", height: 80%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# navbar %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <%# butons %>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", actuality_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Workouts", workouts_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Exercices", exercices_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create a workout", new_workout_path, class: "nav-link active text-white" %>
        </li>

        <%# form search %>

      </ul>
      <% if current_user.present? %>
        <form class="d-flex" role="search">
          <%= link_to "My dashboard", user_my_dashboard_path(current_user.id), class: "text-success nav-link active" %>
        </form>
        <div class="nav-item dropdown ms-3">
              <%= image_tag "profile.jpg", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My workouts", user_my_workouts_path(current_user.id), class: "dropdown-item text-white" %>
                <%= link_to "My dashboard", user_my_dashboard_path(current_user.id), class: "dropdown-item text-white" %>
                <hr class="dropdown-divider">
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
        </div>

      <% else %>

      <% end %>
    </div>

  </div>
</nav>